### ISSUE TITLE
Mainnet contract deployment error

### ISSUE THREAD

**Issue by madhanrajR** [fetchai/fetchd#178]
While trying to deploy the contract on Mainnet I'm facing this issue.

`**failed to execute message; message index: 0: can not create code: unauthorized**  

Mainnet Tx hash : 63BC0BBC1F347BA30050B27E00DAB387CC20190F3821ACC1E77F27F78CE2887E

`

Any suggestions?

Note : Same contract deployed fine on testnet (Stage-world-3)

**Comment by daeMOn63** [comment]
Thanks for reaching out! Indeed wasm code upload and instantiate permissions have been restricted for now due to lots of breaking changes from cosmwasm releases. We're now in the process of upgrading to cosmwasm 1.0.0 in the upcoming days, and lifting such restrictions.

Testnets were not subject to this restriction so what you experienced was all expected.
Keep an eye on next release and please retry once it landed ;)
